language: node_js

node_js:
 - 10.15.3

cache:
  paths:
    - node_modules/
    - functions/node_modules/

before_script:
 - npm install -g firebase-tools
 - cd functions
 - npm ci

script:
  - tslint --project tsconfig.json
  - tsc
  - cd ..
  - ng build --aot --prod

branches:
 only:
  - master

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --only hosting,functions --token $FIREBASE_TOKEN
  on:
    branch: master
